/*
CREATE TABLE persons(
 Id int(10) UNSIGNED NULL DEFAULT NULL,
 FirstName VARCHAR(50) NULL DEFAULT NULL,
 LastName VARCHAR(50) NULL DEFAULT NULL,
 Address VARCHAR(50) NULL DEFAULT NULL,
 Gender VARCHAR(50) NULL DEFAULT NULL
);

ALTER TABLE persons CHANGE Id Id INT(10) AUTO_INCREMENT PRIMARY KEY


CREATE TABLE books(
 Id VARCHAR(10) UNSIGNED NULL DEFAULT NULL PRIMARY KEY,
 Title VARCHAR(50) NULL DEFAULT NULL,
 Author VARCHAR(50) NULL DEFAULT NULL,
 Price NUMERIC(15,2) NULL DEFAULT NULL,
 LaunchDate DATETIME NULL DEFAULT NULL
);

*/